require('dotenv').config();
const express=require('express'),path=require('path'),cors=require('cors'),mongoose=require('mongoose');
const app=express(),PORT=process.env.PORT||3000;app.use(cors());app.use(express.json({limit:'4mb'}));app.use('/api',(req,res,next)=>{res.setHeader('Cache-Control','no-store, no-cache, must-revalidate, proxy-revalidate');res.setHeader('Pragma','no-cache');res.setHeader('Expires','0');next();});app.use(express.static(__dirname));
const auth=require('./api/auth'),state=require('./api/state'),branches=require('./api/branches');app.all('/api/auth',auth);app.all('/api/state',state);app.all('/api/branches',branches);app.get('/api/health',(req,res)=>res.json({ok:true,mongodb:mongoose.connection.readyState===1}));app.use((req,res)=>req.method==='GET'&&!req.path.startsWith('/api/')?res.sendFile(path.join(__dirname,'index.html')):res.status(404).json({error:'Not found'}));
const Branch=branches.Branch;
const Student=mongoose.models.Student||mongoose.model('Student',new mongoose.Schema({id:{type:String,unique:true,required:true},name:String,mobile:String,branch:String,branchId:{type:mongoose.Schema.Types.ObjectId,ref:'Branch',default:null},totalFee:Number,paidFee:Number},{timestamps:true}));
const History=mongoose.models.CollectionHistory||mongoose.model('CollectionHistory',new mongoose.Schema({date:String,velanja:Number,mota:Number,mission:Number,branch:String,branchId:{type:mongoose.Schema.Types.ObjectId,ref:'Branch',default:null},amount:Number},{timestamps:true}));
async function ensureBranches(){const seedNames=[['Velanja','VELANJ'],['Mota Varachha','MOTAVA'],['Mission Road','MISSION']];for(const [name,code] of seedNames){let b=await Branch.findOne({name});if(!b){try{b=await Branch.create({name,code,active:true})}catch(e){b=await Branch.findOne({name})}}}
let all=await Branch.find();
// Turn any legacy branch names already present in student data into real branches.
const legacyNames=await Student.distinct('branch');for(const raw of legacyNames){const name=String(raw||'').trim();if(!name||name==='Unassigned')continue;if(!all.some(b=>b.name===name)){const code=name.replace(/[^A-Za-z0-9]/g,'').slice(0,8).toUpperCase()||('BR'+Date.now().toString().slice(-5));try{await Branch.create({name,code,active:true})}catch(e){}}}
all=await Branch.find();const byName=new Map(all.map(b=>[b.name,b]));
// If the database has no students, restore the supplied original data exactly.
if(await Student.countDocuments()===0){const seed=require('./seed-data.json');if(seed.students?.length)await Student.insertMany(seed.students.map(s=>({id:String(s.id),name:String(s.name||'').trim(),mobile:String(s.mobile||'').trim(),branch:String(s.branch||''),branchId:byName.get(String(s.branch||''))?._id||null,totalFee:s.totalFee==null?null:Number(s.totalFee),paidFee:s.paidFee==null?null:Number(s.paidFee)})));}
// Always repair missing/invalid branch IDs without deleting existing records.
for(const b of all)await Student.updateMany({branch:b.name,$or:[{branchId:null},{branchId:{$exists:false}}]},{$set:{branchId:b._id}});
// No student is allowed to remain unassigned. Legacy blank/unassigned rows go to the first real branch.
const fallback=all[0];if(fallback)await Student.updateMany({$or:[{branch:null},{branch:''},{branch:'Unassigned'},{branchId:null},{branchId:{$exists:false}}]},{$set:{branch:fallback.name,branchId:fallback._id}});
const {BranchUser,hashPw,encPw,DEFAULT_PERMISSIONS}=branches; for(const b of all){let u=await BranchUser.findOne({branchId:b._id});if(!u){const pw=b.code+'@2026';await BranchUser.create({username:b.code.toLowerCase()+'_admin',passwordHash:hashPw(pw),passwordEncrypted:encPw(pw),branchId:b._id,permissions:DEFAULT_PERMISSIONS});}else if(!u.passwordEncrypted){const pw=b.code+'@2026';u.passwordHash=hashPw(pw);u.passwordEncrypted=encPw(pw);await u.save();}if(!u.permissions||u.permissions.size===0){u.permissions=DEFAULT_PERMISSIONS;await u.save();}}
// Convert legacy multi-branch history rows into branch-specific entries once.
const legacy=await History.find({branchId:null}).lean();if(legacy.length){for(const h of legacy){const vals=[['Velanja',h.velanja],['Mota Varachha',h.mota],['Mission Road',h.mission]];for(const [name,val] of vals){if(Number(val||0)!==0){const b=byName.get(name);if(b)await History.create({date:h.date,branch:name,branchId:b._id,amount:Number(val),velanja:null,mota:null,mission:null});}}await History.deleteOne({_id:h._id});}}
if(await History.countDocuments()===0){const seed=require('./seed-data.json');if(seed.history?.length){for(const h of seed.history){for(const [name,val] of [['Velanja',h.velanja],['Mota Varachha',h.mota],['Mission Road',h.mission]])if(Number(val||0)!==0){const b=byName.get(name);if(b)await History.create({date:String(h.date),branch:name,branchId:b._id,amount:Number(val),velanja:null,mota:null,mission:null});}}}}
}
async function start(){if(!process.env.MONGODB_URI){console.error('MONGODB_URI is missing');process.exit(1);}try{await mongoose.connect(process.env.MONGODB_URI,{serverSelectionTimeoutMS:10000});await ensureBranches();app.listen(PORT,()=>console.log(`Server running on http://localhost:${PORT}`));}catch(e){console.error('MongoDB connection failed:',e.message);process.exit(1);}}
if(require.main===module)start();module.exports=app;
