const mongoose = require('mongoose');
const crypto = require('crypto');
const {Branch,BranchUser,checkPw,sign,db,encPw}=require('./branches');
const PASSWORD_KEYS=["pageOpen","studentAdd","studentEdit","studentDelete","collectionAdd","collectionEdit","collectionDelete","excelExport","excelImport"];
const DEFAULT_PASSWORD=process.env.ADMIN_PASSWORD||'1316618'; const MASTER_PASSWORD=process.env.PASSWORD_SETTINGS_MASTER||'Deoxy';
const adminSchema=new mongoose.Schema({key:{type:String,unique:true,default:'main'},passwordHashes:{type:Map,of:String,default:{}},passwordHash:String},{timestamps:true});
const AdminSettings=mongoose.models.AdminSettings||mongoose.model('AdminSettings',adminSchema);
function sha(v){return crypto.createHash('sha256').update(String(v)).digest('hex');}
async function getAdmin(){let a=await AdminSettings.findOne({key:'main'});if(!a){const h=sha(DEFAULT_PASSWORD),o={};PASSWORD_KEYS.forEach(k=>o[k]=h);return AdminSettings.create({key:'main',passwordHash:h,passwordHashes:o});}let ch=false,legacy=a.passwordHash||sha(DEFAULT_PASSWORD);if(!a.passwordHashes||a.passwordHashes.size===0){const o={};PASSWORD_KEYS.forEach(k=>o[k]=legacy);a.passwordHashes=o;ch=true;}else for(const k of PASSWORD_KEYS)if(!a.passwordHashes.get(k)){a.passwordHashes.set(k,legacy);ch=true;}if(ch)await a.save();return a;}
async function verifyKey(k,p){if(!PASSWORD_KEYS.includes(k))return false;const a=await getAdmin();return a.passwordHashes.get(k)===sha(p);}
module.exports=async(req,res)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type,Authorization');res.setHeader('Cache-Control','no-store');if(req.method==='OPTIONS')return res.status(204).end();try{await db();if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const b=req.body||{};
if(b.action==='verify'){const ok=await verifyKey(String(b.key||''),String(b.password||''));return res.status(ok?200:403).json({ok});}
if(b.action==='master'){const ok=String(b.masterPassword||'')===MASTER_PASSWORD;return res.status(ok?200:403).json({ok});}
if(b.action==='changeSettings'){if(String(b.masterPassword||'')!==MASTER_PASSWORD)return res.status(403).json({error:'Wrong master password.'});const a=await getAdmin(),ps=b.passwords||{};for(const k of PASSWORD_KEYS)if(Object.prototype.hasOwnProperty.call(ps,k)){const v=String(ps[k]||'');if(v.length<4)return res.status(400).json({error:k+' password must be at least 4 characters.'});a.passwordHashes.set(k,sha(v));}await a.save();return res.json({ok:true});}
if(b.action==='branchLogin'){const username=String(b.username||'').trim(),password=String(b.password||'');const u=await BranchUser.findOne({username}).populate('branchId');if(!u||!u.branchId||!u.branchId.active||!checkPw(password,u.passwordHash))return res.status(403).json({ok:false,error:'Invalid branch username or password.'});const token=sign({type:'branch',uid:String(u._id),branchId:String(u.branchId._id),username:u.username,branch:u.branchId.name,code:u.branchId.code,permissions:Object.fromEntries(u.permissions||[]),exp:Date.now()+1000*60*60*24*7});return res.json({ok:true,token,user:{username:u.username,branchId:String(u.branchId._id),branch:u.branchId.name,code:u.branchId.code,permissions:Object.fromEntries(u.permissions||[])}});}
return res.status(400).json({error:'Invalid action.'});}catch(e){console.error(e);return res.status(500).json({error:e.message||'Server error'});}};
