const mongoose=require('mongoose');
const {verifyToken,db,Branch}=require('./branches');
const crypto=require('crypto');
const PASSWORD_KEYS=["pageOpen","studentAdd","studentEdit","studentDelete","collectionAdd","collectionEdit","collectionDelete","excelExport","excelImport"];
const adminSchema=new mongoose.Schema({key:{type:String,unique:true,default:'main'},passwordHashes:{type:Map,of:String,default:{}},passwordHash:String},{timestamps:true});
const studentSchema=new mongoose.Schema({id:{type:String,unique:true,required:true},name:String,mobile:String,branch:String,branchId:{type:mongoose.Schema.Types.ObjectId,ref:'Branch',default:null},totalFee:{type:Number,min:0},paidFee:{type:Number,min:0},payments:[{amount:Number,date:String,method:String,note:String,createdAt:{type:Date,default:Date.now}}]},{timestamps:true});
const historySchema=new mongoose.Schema({date:String,velanja:Number,mota:Number,mission:Number,branch:String,branchId:{type:mongoose.Schema.Types.ObjectId,ref:'Branch',default:null},amount:Number},{timestamps:true});
const Student=mongoose.models.Student||mongoose.model('Student',studentSchema);const CollectionHistory=mongoose.models.CollectionHistory||mongoose.model('CollectionHistory',historySchema);const AdminSettings=mongoose.models.AdminSettings||mongoose.model('AdminSettings',adminSchema);
function sha(v){return crypto.createHash('sha256').update(String(v)).digest('hex');}
async function adminOk(req,key){const a=await AdminSettings.findOne({key:'main'});return !!a&&!!a.passwordHashes?.get(key)&&a.passwordHashes.get(key)===sha(String(req.headers['x-admin-password']||''));}
function auth(req){return verifyToken(String(req.headers.authorization||'').replace(/^Bearer\s+/i,''));}
function perm(a,key){return a?.type==='branch' && a.permissions?.[key]!==false;}
async function bootstrapData(){
  const branches=await Branch.find({active:true}).sort({name:1}).lean();
  const byName=new Map(branches.map(b=>[String(b.name).trim().toLowerCase(),b]));
  if(await Student.countDocuments()===0){
    const seed=require('../seed-data.json');
    if(Array.isArray(seed.students)&&seed.students.length){
      const rows=seed.students.map(s=>{const b=byName.get(String(s.branch||'').trim().toLowerCase());return {id:String(s.id),name:String(s.name||'').trim(),mobile:String(s.mobile||'').trim(),branch:b?.name||String(s.branch||'').trim(),branchId:b?._id||null,totalFee:s.totalFee==null?null:Number(s.totalFee),paidFee:s.paidFee==null?null:Number(s.paidFee)};}).filter(s=>s.id&&s.name);
      if(rows.length)try{await Student.insertMany(rows,{ordered:false});}catch(e){}
    }
  }
  for(const b of branches)await Student.updateMany({branch:b.name,$or:[{branchId:null},{branchId:{$exists:false}}]},{$set:{branchId:b._id}});
  if(await CollectionHistory.countDocuments()===0){
    const seed=require('../seed-data.json'); const rows=[];
    for(const h of (seed.history||[])) for(const [name,val] of [['Velanja',h.velanja],['Mota Varachha',h.mota],['Mission Road',h.mission]]){const n=Number(val||0),b=byName.get(name.toLowerCase());if(n&&b)rows.push({date:String(h.date),branch:b.name,branchId:b._id,amount:n,velanja:null,mota:null,mission:null});}
    if(rows.length)try{await CollectionHistory.insertMany(rows,{ordered:false});}catch(e){}
  }
}
function normS(s){return {id:String(s.id||''),name:String(s.name||'').trim(),mobile:String(s.mobile||'').trim(),branch:String(s.branch||''),branchId:s.branchId||null,totalFee:s.totalFee==null||s.totalFee===''?null:Number(s.totalFee),paidFee:s.paidFee==null||s.paidFee===''?null:Number(s.paidFee),payments:Array.isArray(s.payments)?s.payments.map(p=>({amount:Number(p.amount||0),date:String(p.date||''),method:String(p.method||'Cash'),note:String(p.note||''),createdAt:p.createdAt||new Date()})).filter(p=>p.amount>0&&p.date):[]};}
function normH(h){return {date:String(h.date||''),velanja:h.velanja==null||h.velanja===''?null:Number(h.velanja),mota:h.mota==null||h.mota===''?null:Number(h.mota),mission:h.mission==null||h.mission===''?null:Number(h.mission),branch:String(h.branch||''),branchId:h.branchId||null,amount:h.amount==null||h.amount===''?null:Number(h.amount)};}
module.exports=async(req,res)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET,PUT,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type,Authorization,X-Admin-Password,X-Admin-Action,X-Main-Admin');res.setHeader('Cache-Control','no-store');if(req.method==='OPTIONS')return res.status(204).end();try{await db();await bootstrapData();const a=auth(req),main=String(req.headers['x-main-admin']||'')==='true';
if(req.method==='GET'){if(!a&&!main)return res.status(401).json({error:'Login required.'});let branchDoc=null;if(a?.type==='branch')branchDoc=await Branch.findById(a.branchId).lean();const filter=a?.type==='branch'?{branchId:new mongoose.Types.ObjectId(a.branchId)}:{};const [students,history]=await Promise.all([Student.find(filter).sort({id:1}).lean(),CollectionHistory.find(filter).sort({date:1,_id:1}).lean()]);return res.json({students,history,access:a?{type:'branch',branchId:a.branchId,branch:branchDoc?.name||a.branch||'',code:branchDoc?.code||a.code||'',username:a.username,permissions:a.permissions||{}}:{type:'main'}});}
if(req.method!=='PUT')return res.status(405).json({error:'Method not allowed'});const key=String(req.headers['x-admin-action']||'pageOpen');if(a){if(!perm(a,key))return res.status(403).json({error:'This action is not allowed for your branch.'});}else if(!(await adminOk(req,key)))return res.status(403).json({error:'Wrong password.'});const body=req.body||{};if(!Array.isArray(body.students)||!Array.isArray(body.history))return res.status(400).json({error:'students and history must be arrays'});
const students=body.students.map(normS).filter(s=>s.id&&s.name);const history=body.history.map(normH).filter(h=>h.date);for(const s of students){if(s.totalFee!=null&&(!Number.isFinite(s.totalFee)||s.totalFee<0))return res.status(400).json({error:'Total Fee must be 0 or greater.'});if(s.paidFee!=null&&(!Number.isFinite(s.paidFee)||s.paidFee<0))return res.status(400).json({error:'Paid Fee must be 0 or greater.'});if(s.totalFee!=null&&s.paidFee!=null&&s.paidFee>s.totalFee)return res.status(400).json({error:`Paid Fee cannot exceed Total Fee for ${s.id}.`});}if(a){const bid=new mongoose.Types.ObjectId(a.branchId);const branchDoc=await Branch.findById(bid).lean();if(!branchDoc||!branchDoc.active)return res.status(403).json({error:'Your branch is inactive or missing.'});for(const s of students)if(String(s.branchId||bid)!==String(bid))return res.status(403).json({error:'Every student must belong to your branch.'});for(const h of history)if(h.branchId&&String(h.branchId)!==String(bid))return res.status(403).json({error:'Branch history access violation.'});const cleanStudents=students.map(s=>({...s,branchId:bid,branch:branchDoc.name}));const ids=cleanStudents.map(s=>s.id);const conflicting=await Student.find({id:{$in:ids},branchId:{$ne:bid}}).select('id branch branchId').lean();if(conflicting.length)return res.status(409).json({error:'Student ID already belongs to another branch: '+conflicting.map(x=>x.id).join(', ')+'. Please use a new Student ID.'});await Student.deleteMany({branchId:bid,id:{$nin:ids}});for(const s of cleanStudents)await Student.updateOne({id:s.id,branchId:bid},{$set:s},{upsert:true});await CollectionHistory.deleteMany({branchId:bid});if(history.length)await CollectionHistory.insertMany(history.map(h=>({...h,branchId:bid,branch:branchDoc.name,amount:h.amount==null?0:h.amount,velanja:null,mota:null,mission:null})));}else{const ids=students.map(s=>s.id);await Student.deleteMany({id:{$nin:ids}});for(const s of students)await Student.updateOne({id:s.id},{$set:s},{upsert:true});await CollectionHistory.deleteMany({});if(history.length)await CollectionHistory.insertMany(history);}
const filter=a?{branchId:new mongoose.Types.ObjectId(a.branchId)}:{};const [savedStudents,savedHistory]=await Promise.all([Student.find(filter).sort({id:1}).lean(),CollectionHistory.find(filter).sort({date:1,_id:1}).lean()]);return res.json({students:savedStudents,history:savedHistory});}catch(e){console.error(e);return res.status(500).json({error:e.message||'Server error'});}};
