const mongoose=require('mongoose');
const {verifyToken,db,Branch}=require('./branches');
const crypto=require('crypto');
const PASSWORD_KEYS=["pageOpen","studentAdd","studentEdit","studentDelete","collectionAdd","collectionEdit","collectionDelete","commissionPayoutAdd","commissionPayoutEdit","commissionPayoutDelete","excelExport","excelImport"];

const adminSchema=new mongoose.Schema({key:{type:String,unique:true,default:'main'},passwordHashes:{type:Map,of:String,default:{}},passwordHash:String},{timestamps:true});
const paymentSchema=new mongoose.Schema({date:String,amount:Number,note:String},{_id:false});
const studentSchema=new mongoose.Schema({id:{type:String,unique:true,required:true},name:String,mobile:String,branch:String,branchId:{type:mongoose.Schema.Types.ObjectId,ref:'Branch',default:null},totalFee:Number,paidFee:Number,commissionPaid:{type:Number,default:0},payments:{type:[paymentSchema],default:[]}},{timestamps:true});
const historySchema=new mongoose.Schema({date:String,velanja:Number,mota:Number,mission:Number,branch:String,branchId:{type:mongoose.Schema.Types.ObjectId,ref:'Branch',default:null},amount:Number},{timestamps:true});
const payoutSchema=new mongoose.Schema({date:String,branch:String,branchId:{type:mongoose.Schema.Types.ObjectId,ref:'Branch',default:null},amount:Number,note:String},{timestamps:true});
const Student=mongoose.models.Student||mongoose.model('Student',studentSchema);const CollectionHistory=mongoose.models.CollectionHistory||mongoose.model('CollectionHistory',historySchema);const CommissionPayout=mongoose.models.CommissionPayout||mongoose.model('CommissionPayout',payoutSchema);const AdminSettings=mongoose.models.AdminSettings||mongoose.model('AdminSettings',adminSchema);
function sha(v){return crypto.createHash('sha256').update(String(v)).digest('hex');}
async function adminOk(req,key){const a=await AdminSettings.findOne({key:'main'});return !!a&&!!a.passwordHashes?.get(key)&&a.passwordHashes.get(key)===sha(String(req.headers['x-admin-password']||''));}
function auth(req){return verifyToken(String(req.headers.authorization||'').replace(/^Bearer\s+/i,''));}
function perm(a,key){return a?.type==='branch' && a.permissions?.[key]!==false;}
async function bootstrapData(){
  const branches=await Branch.find({active:true}).sort({name:1}).lean();
  const byName=new Map(branches.map(b=>[String(b.name).trim().toLowerCase(),b]));
  if(await Student.countDocuments()===0){
    const seed=require('../seed-data.json');
    if(Array.isArray(seed.students)&&seed.students.length){
      const rows=seed.students.map(s=>{const b=byName.get(String(s.branch||'').trim().toLowerCase());return {id:String(s.id),name:String(s.name||'').trim(),mobile:String(s.mobile||'').trim(),branch:b?.name||String(s.branch||'').trim(),branchId:b?._id||null,totalFee:s.totalFee==null?null:Number(s.totalFee),paidFee:s.paidFee==null?null:Number(s.paidFee)};}).filter(s=>s.id&&s.name);
      if(rows.length)try{await Student.insertMany(rows,{ordered:false});}catch(e){}
    }
  }
  for(const b of branches)await Student.updateMany({branch:b.name,$or:[{branchId:null},{branchId:{$exists:false}}]},{$set:{branchId:b._id}});
  if(await CollectionHistory.countDocuments()===0){
    const seed=require('../seed-data.json'); const rows=[];
    for(const h of (seed.history||[])) for(const [name,val] of [['Velanja',h.velanja],['Mota Varachha',h.mota],['Mission Road',h.mission]]){const n=Number(val||0),b=byName.get(name.toLowerCase());if(n&&b)rows.push({date:String(h.date),branch:b.name,branchId:b._id,amount:n,velanja:null,mota:null,mission:null});}
    if(rows.length)try{await CollectionHistory.insertMany(rows,{ordered:false});}catch(e){}
  }
}
function normS(s){return {id:String(s.id||''),name:String(s.name||'').trim(),mobile:String(s.mobile||'').trim(),branch:String(s.branch||''),branchId:s.branchId||null,totalFee:s.totalFee==null||s.totalFee===''?null:Number(s.totalFee),paidFee:s.paidFee==null||s.paidFee===''?null:Number(s.paidFee),commissionPaid:Number(s.commissionPaid||0),payments:Array.isArray(s.payments)?s.payments.map(x=>({date:String(x.date||''),amount:Number(x.amount||0),note:String(x.note||'')})).filter(x=>x.date&&x.amount>0):[]};}
function normH(h){return {date:String(h.date||''),velanja:h.velanja==null||h.velanja===''?null:Number(h.velanja),mota:h.mota==null||h.mota===''?null:Number(h.mota),mission:h.mission==null||h.mission===''?null:Number(h.mission),branch:String(h.branch||''),branchId:h.branchId||null,amount:h.amount==null||h.amount===''?null:Number(h.amount)};}
function normP(h){return {date:String(h.date||''),branch:String(h.branch||''),branchId:h.branchId||null,amount:Number(h.amount||0),note:String(h.note||'')};}
module.exports=async(req,res)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET,PUT,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type,Authorization,X-Admin-Password,X-Admin-Action,X-Main-Admin');res.setHeader('Cache-Control','no-store');if(req.method==='OPTIONS')return res.status(204).end();try{await db();await bootstrapData();const a=auth(req),main=String(req.headers['x-main-admin']||'')==='true';
const requestedKey=String(req.headers['x-admin-action']||'pageOpen');
const adminOverride=!!(a?.type==='branch' && String(req.headers['x-admin-password']||'') && (await adminOk(req,requestedKey)));
if(req.method==='GET'){if(!a&&!main)return res.status(401).json({error:'Login required.'});let branchDoc=null;if(a?.type==='branch')branchDoc=await Branch.findById(a.branchId).lean();const filter=a?.type==='branch'?{$or:[{branchId:new mongoose.Types.ObjectId(a.branchId)},{branch:branchDoc?.name}]}:{};const [students,history,payouts]=await Promise.all([Student.find(filter).sort({id:1}).lean(),CollectionHistory.find(filter).sort({date:1,_id:1}).lean(),CommissionPayout.find(filter).sort({date:1,_id:1}).lean()]);return res.json({students,history,payouts,access:a?{type:'branch',branchId:a.branchId,branch:branchDoc?.name||a.branch||'',code:branchDoc?.code||a.code||'',username:a.username,permissions:a.permissions||{}}:{type:'main'}});}
if(req.method!=='PUT')return res.status(405).json({error:'Method not allowed'});const key=requestedKey;if(a){if(!adminOverride&&!perm(a,key))return res.status(403).json({error:'Editing this branch requires the main admin password.'});}else if(!(await adminOk(req,key)))return res.status(403).json({error:'Wrong password.'});const body=req.body||{};if(!Array.isArray(body.students)||!Array.isArray(body.history))return res.status(400).json({error:'students and history must be arrays'});
const students=body.students.map(normS).filter(s=>s.id&&s.name);const history=body.history.map(normH).filter(h=>h.date);const payouts=Array.isArray(body.payouts)?body.payouts.map(normP).filter(h=>h.date&&h.amount>0):[];if(a){const bid=new mongoose.Types.ObjectId(a.branchId);const branchDoc=await Branch.findById(bid).lean();if(!branchDoc||!branchDoc.active)return res.status(403).json({error:'Your branch is inactive or missing.'});for(const s of students)if(String(s.branchId||bid)!==String(bid))return res.status(403).json({error:'Every student must belong to your branch.'});for(const h of history)if(h.branchId&&String(h.branchId)!==String(bid))return res.status(403).json({error:'Branch history access violation.'});for(const h of payouts)if(h.branchId&&String(h.branchId)!==String(bid))return res.status(403).json({error:'Branch payout access violation.'});const cleanStudents=students.map(s=>({...s,branchId:bid,branch:branchDoc.name}));await Student.deleteMany({branchId:bid,id:{$nin:cleanStudents.map(s=>s.id)}});for(const s of cleanStudents)await Student.updateOne({id:s.id},{$set:s},{upsert:true});await CollectionHistory.deleteMany({branchId:bid});if(history.length)await CollectionHistory.insertMany(history.map(h=>({...h,branchId:bid,branch:branchDoc.name,amount:h.amount==null?0:h.amount,velanja:null,mota:null,mission:null})));await CommissionPayout.deleteMany({branchId:bid});if(payouts.length)await CommissionPayout.insertMany(payouts.map(h=>({...h,branchId:bid,branch:branchDoc.name})));}else{const ids=students.map(s=>s.id);await Student.deleteMany({id:{$nin:ids}});for(const s of students)await Student.updateOne({id:s.id},{$set:s},{upsert:true});await CollectionHistory.deleteMany({});if(history.length)await CollectionHistory.insertMany(history);await CommissionPayout.deleteMany({});if(payouts.length)await CommissionPayout.insertMany(payouts);}
const filter=a?{$or:[{branchId:new mongoose.Types.ObjectId(a.branchId)},{branch:(await Branch.findById(a.branchId).lean())?.name}]}:{};const [savedStudents,savedHistory,savedPayouts]=await Promise.all([Student.find(filter).sort({id:1}).lean(),CollectionHistory.find(filter).sort({date:1,_id:1}).lean(),CommissionPayout.find(filter).sort({date:1,_id:1}).lean()]);return res.json({students:savedStudents,history:savedHistory,payouts:savedPayouts});}catch(e){console.error(e);return res.status(500).json({error:e.message||'Server error'});}};
